# Site settings
title: Content Strategy – Accessibility & Multi-Screen Design
email: mail@yatil.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cos.accessibility.rocks" # the base hostname & protocol for your site
twitter_username: yatil
github_username:  yatil

# Build settings
markdown: kramdown

timezone: Europe/Berlin

permalink: /:categories/:year-:month-:day/

exclude: [vendor]

future: true

collections:
  cos14:
    output: true
    permalink: /cos14/:title/
    future: true
  cos15:
    output: true
    permalink: /cos15/:title/
    future: true
  cos16:
    output: true
    permalink: /cos16/:title/
    future: true
  cos17:
    output: true
    permalink: /cos17/:title/
    future: true